//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro, programa fora dos parâmetros.
        /// </summary>
        internal static string Analyzer_VerifyToDelete {
            get {
                return ResourceManager.GetString("Analyzer_VerifyToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem arquivos a sincronizar!.
        /// </summary>
        internal static string Folder_NotFilesFound {
            get {
                return ResourceManager.GetString("Folder_NotFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja copiar {0} para {1}?.
        /// </summary>
        internal static string Folder_SureCopy {
            get {
                return ResourceManager.GetString("Folder_SureCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja substituir o arquivo {0} em {1}?\nData antiga: {2}\nData nova: {3}.
        /// </summary>
        internal static string Folder_SureOverwrite {
            get {
                return ResourceManager.GetString("Folder_SureOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} arquivo(s) a sincronizar!.
        /// </summary>
        internal static string Folder_SyncFilesCount {
            get {
                return ResourceManager.GetString("Folder_SyncFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
    }
}
